import { Bus, Driver, Route, Student, Attendance, Complaint, Notification, User, Stop, AttendanceStatus, SalaryRecord, FeeRecord, Emergency, VehicleInspection, FuelLog, TripRecord, CalendarScheduleEvent } from '@/types';
import { addDays, subDays } from 'date-fns';

const today = new Date();
const todayStr = today.toISOString();

export const mockBuses: Bus[] = [
  { id: 'b1', busNumber: 'BUS-001', registrationNumber: 'TN-33-AB-1201', busName: 'BIT Bus A', capacity: 60, driverId: 'd1', routeId: 'r1', fuelType: 'Diesel', averageMileage: 4.5, status: 'active', notes: 'Regular maintenance done' },
  { id: 'b2', busNumber: 'BUS-002', registrationNumber: 'TN-33-AB-1202', busName: 'BIT Bus B', capacity: 50, driverId: 'd2', routeId: 'r2', fuelType: 'Diesel', averageMileage: 5.0, status: 'active' },
  { id: 'b3', busNumber: 'BUS-003', registrationNumber: 'TN-33-AB-1203', busName: 'BIT Bus C', capacity: 50, driverId: 'd3', routeId: 'r3', fuelType: 'Diesel', averageMileage: 4.8, status: 'active' },
  { id: 'b4', busNumber: 'BUS-004', registrationNumber: 'TN-33-AB-1204', busName: 'BIT Bus D', capacity: 40, driverId: 'd4', routeId: 'r4', fuelType: 'Diesel', averageMileage: 5.2, status: 'active' },
];

export const mockDrivers: Driver[] = [
  { id: 'd1', name: 'S. Kumar', email: 'kumar.s@bitsathy.ac.in', role: 'driver', employeeId: 'DRV-001', licenseNumber: 'TN-DL-12345', licenseExpiry: '2028-05-12', experience: 5, phone: '9876543210', status: 'active', assignedBusId: 'b1', assignedRouteId: 'r1' },
  { id: 'd2', name: 'R. Murugan', email: 'murugan.r@bitsathy.ac.in', role: 'driver', employeeId: 'DRV-002', licenseNumber: 'TN-DL-67890', licenseExpiry: '2027-11-20', experience: 8, phone: '9876543211', status: 'active', assignedBusId: 'b2', assignedRouteId: 'r2' },
  { id: 'd3', name: 'M. Karthikeyan', email: 'karthikeyan.m@bitsathy.ac.in', role: 'driver', employeeId: 'DRV-003', licenseNumber: 'TN-DL-54321', licenseExpiry: '2029-01-15', experience: 3, phone: '9876543212', status: 'active', assignedBusId: 'b3', assignedRouteId: 'r3' },
  { id: 'd4', name: 'V. Prakash', email: 'prakash.v@bitsathy.ac.in', role: 'driver', employeeId: 'DRV-004', licenseNumber: 'TN-DL-98765', licenseExpiry: '2026-08-30', experience: 12, phone: '9876543213', status: 'active', assignedBusId: 'b4', assignedRouteId: 'r4' },
];

export const mockRoutes: Route[] = [
  {
    id: 'r1',
    name: 'Route A',
    distance: '35 km',
    distanceKm: 35,
    estimatedTime: '55 mins',
    stops: [
      { id: 's1-1', name: 'Annur Bus Stand', latitude: 11.2333, longitude: 77.1000, order: 1 },
      { id: 's1-2', name: 'Kunnathur', latitude: 11.2500, longitude: 77.1500, order: 2 },
      { id: 's1-3', name: 'Kovilpalayam', latitude: 11.2800, longitude: 77.1800, order: 3 },
      { id: 's1-4', name: 'Sathyamangalam', latitude: 11.5030, longitude: 77.2400, order: 4 },
      { id: 's1-5', name: 'Bannari', latitude: 11.5032, longitude: 77.2500, order: 5 },
      { id: 's1-6', name: 'BIT Campus', latitude: 11.5034, longitude: 77.2714, order: 6 },
    ],
  },
  {
    id: 'r2',
    name: 'Route B',
    distance: '65 km',
    distanceKm: 65,
    estimatedTime: '90 mins',
    stops: [
      { id: 's2-1', name: 'Gandhipuram', latitude: 11.0183, longitude: 76.9660, order: 1 },
      { id: 's2-2', name: 'Saibaba Colony', latitude: 11.0300, longitude: 76.9500, order: 2 },
      { id: 's2-3', name: 'Saravanampatti', latitude: 11.0820, longitude: 76.9930, order: 3 },
      { id: 's2-4', name: 'Kovilpalayam', latitude: 11.1640, longitude: 77.0420, order: 4 },
      { id: 's2-5', name: 'Annur', latitude: 11.2333, longitude: 77.1000, order: 5 },
      { id: 's2-6', name: 'Sathyamangalam', latitude: 11.5030, longitude: 77.2400, order: 6 },
      { id: 's2-7', name: 'BIT Campus', latitude: 11.5034, longitude: 77.2714, order: 7 },
    ],
  },
  {
    id: 'r3',
    name: 'Route C',
    distance: '60 km',
    distanceKm: 60,
    estimatedTime: '80 mins',
    stops: [
      { id: 's3-1', name: 'Erode Bus Stand', latitude: 11.3410, longitude: 77.7170, order: 1 },
      { id: 's3-2', name: 'Perundurai', latitude: 11.2700, longitude: 77.5800, order: 2 },
      { id: 's3-3', name: 'Bhavani', latitude: 11.4500, longitude: 77.6800, order: 3 },
      { id: 's3-4', name: 'Sathyamangalam', latitude: 11.5030, longitude: 77.2400, order: 4 },
      { id: 's3-5', name: 'Bannari', latitude: 11.5032, longitude: 77.2500, order: 5 },
      { id: 's3-6', name: 'BIT Campus', latitude: 11.5034, longitude: 77.2714, order: 6 },
    ],
  },
  {
    id: 'r4',
    name: 'Route D',
    distance: '45 km',
    distanceKm: 45,
    estimatedTime: '60 mins',
    stops: [
      { id: 's4-1', name: 'Bhavani Bus Stand', latitude: 11.4500, longitude: 77.6830, order: 1 },
      { id: 's4-2', name: 'Kavindapadi', latitude: 11.4200, longitude: 77.5800, order: 2 },
      { id: 's4-3', name: 'Athani', latitude: 11.5200, longitude: 77.5300, order: 3 },
      { id: 's4-4', name: 'Sathyamangalam', latitude: 11.5030, longitude: 77.2400, order: 4 },
      { id: 's4-5', name: 'Bannari', latitude: 11.5032, longitude: 77.2500, order: 5 },
      { id: 's4-6', name: 'BIT Campus', latitude: 11.5034, longitude: 77.2714, order: 6 },
    ],
  }
];

const studentNames = [
  'Arun Kumar', 'Rishvanth K', 'Praveen S', 'Hariharan M', 'Sanjay R', 'Karthikeyan V', 'Mohamed Irfan', 'Vignesh Kumar', 'Akash B', 'Harish Kumar', 
  'Deepak R', 'Naveen Kumar', 'Rahul S', 'Dinesh K', 'Gokul Raj', 'Abishek M', 'Yogesh V', 'Nithish Kumar', 'Ashwin R', 'Surya Prakash', 
  'Vikram S', 'Manoj K', 'Prasanth D', 'Santhosh M', 'Vijay R', 'Gowtham V', 'Ajith Kumar', 'Balaji S', 'Dhruv M', 'Kishore K', 
  'Manikandan P', 'Nandha Kumar', 'Prakash Raj', 'Ramesh S', 'Saravanan M', 'Tharun V', 'Venkatesh R', 'Yuvraj M', 'Sathish Kumar', 'Rajesh K', 
  'Nagaraj P', 'Kannan V', 'Jeeva S', 'Dhanush M', 'Bhuvanesh R', 'Aravind K', 'Vasanth S', 'Sriram M', 'Ponnusamy R', 'Murugesan K', 
  'Lakshman V', 'Jagan S', 'Hari Krishna', 'Ganesan M', 'Elango R', 'Deva K', 'Chandra Sekar', 'Babu M', 'Anand S', 'Vinoth Kumar'
];

const departments = [
  'Computer Science', 'Artificial Intelligence', 'Information Technology', 'Electronics and Communication', 
  'Electrical and Electronics', 'Mechanical', 'Civil', 'Biotechnology'
];

const years = ['I Year', 'II Year', 'III Year', 'IV Year'];

// Weighted distribution for realistic attendance statuses
const statuses: AttendanceStatus[] = [
  'present', 'present', 'present', 'present', 'present', 'present', 'present', 
  'absent', 'late', 'leave'
];

export const mockStudents: Student[] = studentNames.map((name, index) => {
  const route = mockRoutes[index % mockRoutes.length];
  // Assign to stops excluding the final BIT Campus stop
  const pickupStops = route.stops.slice(0, -1); 
  const stop = pickupStops[index % pickupStops.length];
  const busId = `b${(index % mockRoutes.length) + 1}`;
  
  return {
    id: `st${index + 1}`,
    name,
    email: `${name.toLowerCase().replace(' ', '.')}@bitsathy.ac.in`,
    role: 'student',
    studentId: `${departments[index % departments.length].substring(0, 3).toUpperCase()}${(2024 - (index % 4)).toString()}-${(index + 1).toString().padStart(3, '0')}`,
    registerNumber: `73042${(index % 4) + 1}104${(index + 1).toString().padStart(3, '0')}`,
    department: departments[index % departments.length],
    year: years[index % years.length],
    phone: `98765${index.toString().padStart(5, '0')}`,
    assignedBusId: busId,
    assignedRouteId: route.id,
    pickupStopId: stop.id,
  };
});

export const mockAttendance: Attendance[] = mockStudents.map((student, index) => ({
  id: `a${index + 1}`,
  studentId: student.id,
  busId: student.assignedBusId!,
  date: todayStr,
  status: statuses[index % statuses.length],
}));

export const mockUsers: User[] = [
  { id: 'u1', name: 'Admin User', email: 'admin@college.edu', role: 'admin' },
  { id: 'd1', name: 'S. Kumar', email: 'kumar.s@bitsathy.ac.in', role: 'driver' }, // maps to mockDrivers[0]
  { id: 'st1', name: 'Arun Kumar', email: 'arun.kumar@bitsathy.ac.in', role: 'student' }, // maps to mockStudents[0]
];

export const mockComplaints: Complaint[] = [
  { id: 'c1', userId: 'st1', subject: 'Late Bus', description: 'Bus was 20 minutes late at Annur.', status: 'pending', date: subDays(today, 2).toISOString() },
  { id: 'c2', userId: 'st2', subject: 'AC not working', description: 'The air conditioning in BUS-02 is broken.', status: 'in-progress', date: subDays(today, 1).toISOString() },
];

export const mockNotifications: Notification[] = [
  { id: 'n1', title: 'Route Change', message: 'Tomorrow morning all buses will depart 15 minutes earlier due to road maintenance.', category: 'Route Update', priority: 'medium', targetRole: 'all', recipientType: 'all', status: 'sent', date: today.toISOString(), readBy: [], deletedBy: [] },
  { id: 'n2', title: 'Maintenance', message: 'BUS-003 is scheduled for maintenance this weekend.', category: 'Maintenance Notice', priority: 'low', targetRole: 'driver', recipientType: 'all_drivers', status: 'sent', date: subDays(today, 1).toISOString(), readBy: ['d1', 'd2'], deletedBy: [] },
  { id: 'n3', title: 'Bus Delay', message: 'Bus A is delayed by 10 minutes.', category: 'Bus Delay', priority: 'high', targetRole: 'all', recipientType: 'route_students', recipientIds: ['r1'], status: 'sent', date: new Date(today.getTime() - 1000 * 60 * 30).toISOString(), readBy: [], deletedBy: [] },
  { id: 'n4', title: 'Holiday Notice', message: 'Transport services are unavailable on Independence Day.', category: 'Holiday Notice', priority: 'medium', targetRole: 'all', recipientType: 'all', status: 'sent', date: subDays(today, 3).toISOString(), readBy: ['st1', 'd1'], deletedBy: [] },
  { id: 'n5', title: 'Placement Drive', message: 'Special buses have been arranged for Placement Drive.', category: 'General Announcement', priority: 'low', targetRole: 'student', recipientType: 'all_students', status: 'sent', date: new Date(today.getTime() - 1000 * 60 * 60 * 2).toISOString(), readBy: [], deletedBy: [] },
  { id: 'n6', title: 'Bus Reassigned', message: 'Bus C has been reassigned due to maintenance.', category: 'Bus Breakdown', priority: 'emergency', targetRole: 'specific', recipientType: 'bus_drivers', recipientIds: ['b3'], status: 'sent', date: subDays(today, 2).toISOString(), readBy: [], deletedBy: [] },
];

export const mockSalaryRecords: SalaryRecord[] = [
  {
    id: 'sal-1',
    driverId: 'd1',
    driverName: 'S. Kumar',
    employeeId: 'DRV-001',
    month: 'August 2026',
    basicSalary: 32000,
    allowances: 5000,
    bonus: 2000,
    deductions: 1500,
    netSalary: 37500,
    paymentStatus: 'paid',
    paymentDate: '01 August 2026',
    paymentMethod: 'Net Banking',
    bankName: 'State Bank of India',
    accountNumberMasked: '•••• •••• 4829',
    ifscCode: 'SBIN0001234',
    transactionId: 'TXN240801001',
  },
  {
    id: 'sal-2',
    driverId: 'd2',
    driverName: 'R. Murugan',
    employeeId: 'DRV-002',
    month: 'August 2026',
    basicSalary: 36000,
    allowances: 5000,
    bonus: 2500,
    deductions: 1500,
    netSalary: 42000,
    paymentStatus: 'paid',
    paymentDate: '01 August 2026',
    paymentMethod: 'Net Banking',
    bankName: 'HDFC Bank',
    accountNumberMasked: '•••• •••• 9102',
    ifscCode: 'HDFC0005678',
    transactionId: 'TXN240801002',
  },
  {
    id: 'sal-3',
    driverId: 'd3',
    driverName: 'M. Karthikeyan',
    employeeId: 'DRV-003',
    month: 'August 2026',
    basicSalary: 35000,
    allowances: 6000,
    bonus: 5000,
    deductions: 1000,
    netSalary: 45000,
    paymentStatus: 'pending',
    paymentDate: null,
    paymentMethod: 'Net Banking',
    bankName: 'ICICI Bank',
    accountNumberMasked: '•••• •••• 7731',
    ifscCode: 'ICIC0009876',
    transactionId: null,
  },
  {
    id: 'sal-4',
    driverId: 'd4',
    driverName: 'V. Prakash',
    employeeId: 'DRV-004',
    month: 'August 2026',
    basicSalary: 40000,
    allowances: 7000,
    bonus: 3000,
    deductions: 2000,
    netSalary: 48000,
    paymentStatus: 'pending',
    paymentDate: null,
    paymentMethod: 'Net Banking',
    bankName: 'Axis Bank',
    accountNumberMasked: '•••• •••• 3341',
    ifscCode: 'UTIB0004321',
    transactionId: null,
  },
];

export const mockFeeRecords: FeeRecord[] = [
  {
    id: 'fee-1',
    studentId: 'st1',
    studentName: 'Arun Kumar',
    registerNumber: '7376221CS101',
    routeId: 'r1',
    routeName: 'Route A',
    busId: 'b1',
    busNumber: 'BUS-001',
    semester: 'Semester 5 (Odd 2026)',
    transportFee: 18000,
    lateFee: 500,
    scholarshipDiscount: 0,
    totalAmount: 18500,
    paidAmount: 18500,
    pendingAmount: 0,
    dueDate: '15 August 2026',
    paymentStatus: 'paid',
    lastPaymentDate: '01 August 2026',
    paymentMethod: 'Net Banking',
    transactionId: 'TRN240801001',
  },
  {
    id: 'fee-2',
    studentId: 'st2',
    studentName: 'Rishvanth K',
    registerNumber: '7376221CS102',
    routeId: 'r2',
    routeName: 'Route B',
    busId: 'b2',
    busNumber: 'BUS-002',
    semester: 'Semester 5 (Odd 2026)',
    transportFee: 22000,
    lateFee: 0,
    scholarshipDiscount: 2000,
    totalAmount: 20000,
    paidAmount: 0,
    pendingAmount: 20000,
    dueDate: '20 August 2026',
    paymentStatus: 'pending',
    lastPaymentDate: null,
    paymentMethod: null,
    transactionId: null,
  },
  {
    id: 'fee-3',
    studentId: 'st3',
    studentName: 'Praveen S',
    registerNumber: '7376221CS103',
    routeId: 'r3',
    routeName: 'Route C',
    busId: 'b3',
    busNumber: 'BUS-003',
    semester: 'Semester 5 (Odd 2026)',
    transportFee: 19500,
    lateFee: 0,
    scholarshipDiscount: 1500,
    totalAmount: 18000,
    paidAmount: 18000,
    pendingAmount: 0,
    dueDate: '10 August 2026',
    paymentStatus: 'paid',
    lastPaymentDate: '28 July 2026',
    paymentMethod: 'UPI',
    transactionId: 'TRN240801002',
  },
  {
    id: 'fee-4',
    studentId: 'st4',
    studentName: 'Hariharan M',
    registerNumber: '7376221CS104',
    routeId: 'r4',
    routeName: 'Route D',
    busId: 'b4',
    busNumber: 'BUS-004',
    semester: 'Semester 5 (Odd 2026)',
    transportFee: 17000,
    lateFee: 500,
    scholarshipDiscount: 0,
    totalAmount: 17500,
    paidAmount: 0,
    pendingAmount: 17500,
    dueDate: '25 August 2026',
    paymentStatus: 'pending',
    lastPaymentDate: null,
    paymentMethod: null,
    transactionId: null,
  },
  {
    id: 'fee-5',
    studentId: 'st5',
    studentName: 'Sanjay R',
    registerNumber: '7376221CS105',
    routeId: 'r1',
    routeName: 'Route A',
    busId: 'b1',
    busNumber: 'BUS-001',
    semester: 'Semester 5 (Odd 2026)',
    transportFee: 18000,
    lateFee: 0,
    scholarshipDiscount: 1000,
    totalAmount: 17000,
    paidAmount: 17000,
    pendingAmount: 0,
    dueDate: '15 August 2026',
    paymentStatus: 'paid',
    lastPaymentDate: '30 July 2026',
    paymentMethod: 'Debit Card',
    transactionId: 'TRN240801003',
  },
];

export const mockEmergencies: Emergency[] = [
  {
    id: 'EMG-101',
    reportedBy: 'student',
    reporterName: 'Arun Kumar',
    reporterId: 'st1',
    registerNumber: '7376221CS101',
    busId: 'b1',
    busNumber: 'BUS-001',
    routeId: 'r1',
    routeName: 'Route A',
    pickupPoint: 'Annur Bus Stand',
    latitude: 11.2333,
    longitude: 77.1000,
    emergencyType: 'Medical Emergency',
    priority: 'critical',
    description: 'Student experiencing severe dizziness and breathing discomfort.',
    emergencyContact: '+91 98765 43210',
    date: todayStr,
    status: 'Active',
    assignedStaff: 'Unassigned',
    remarks: 'Awaiting Campus Medical Dispatch',
  },
  {
    id: 'EMG-102',
    reportedBy: 'driver',
    reporterName: 'S. Kumar',
    reporterId: 'd1',
    employeeId: 'DRV-001',
    busId: 'b1',
    busNumber: 'BUS-001',
    routeId: 'r1',
    routeName: 'Route A',
    pickupPoint: 'Kovilpalayam',
    latitude: 11.1575,
    longitude: 77.0392,
    emergencyType: 'Vehicle Breakdown',
    priority: 'high',
    description: 'Engine overheating issue near Kovilpalayam junction. Replacement bus requested.',
    emergencyContact: '+91 98765 43210',
    date: subDays(today, 1).toISOString(),
    status: 'In Progress',
    assignedStaff: 'Officer Senthil (Transport Unit)',
    remarks: 'Backup Bus BUS-004 dispatched to pick up students.',
    actionTaken: 'Backup bus deployed.',
  },
  {
    id: 'EMG-103',
    reportedBy: 'student',
    reporterName: 'Rishvanth K',
    reporterId: 'st2',
    registerNumber: '7376221CS102',
    busId: 'b2',
    busNumber: 'BUS-002',
    routeId: 'r2',
    routeName: 'Route B',
    pickupPoint: 'Gandhipuram',
    latitude: 11.0183,
    longitude: 76.9667,
    emergencyType: 'Traffic Delay',
    priority: 'medium',
    description: 'Heavy traffic congestion due to rally. Delay estimated 30 mins.',
    emergencyContact: '+91 98765 43211',
    date: subDays(today, 2).toISOString(),
    status: 'Resolved',
    assignedStaff: 'Control Room Officer',
    remarks: 'Traffic cleared, bus arrived safely.',
    actionTaken: 'Notified all route students via app alert.',
  },
];

export const mockInspections: VehicleInspection[] = [
  {
    id: 'insp-101',
    driverId: 'd1',
    driverName: 'S. Kumar',
    busId: 'b1',
    busNumber: 'BUS-001',
    routeId: 'r1',
    routeName: 'Route A',
    date: todayStr,
    time: '07:15 AM',
    checklist: {
      brakes: true,
      tyres: true,
      headlights: true,
      indicators: true,
      horn: true,
      mirrors: true,
      windshield: true,
      fuelLevel: true,
      battery: true,
      fireExtinguisher: true,
      firstAidKit: true,
      emergencyExit: true,
    },
    additionalRemarks: 'All pre-trip safety checks cleared successfully.',
    status: 'Good',
  },
  {
    id: 'insp-102',
    driverId: 'd2',
    driverName: 'M. Ramesh',
    busId: 'b2',
    busNumber: 'BUS-002',
    routeId: 'r2',
    routeName: 'Route B',
    date: subDays(today, 1).toISOString(),
    time: '07:20 AM',
    checklist: {
      brakes: true,
      tyres: false,
      headlights: true,
      indicators: true,
      horn: true,
      mirrors: true,
      windshield: true,
      fuelLevel: true,
      battery: true,
      fireExtinguisher: true,
      firstAidKit: true,
      emergencyExit: true,
    },
    additionalRemarks: 'Rear left tyre pressure slightly low. Needs top-up.',
    status: 'Needs Maintenance',
  },
];

export const mockFuelLogs: FuelLog[] = [
  {
    id: 'fuel-101',
    driverId: 'd1',
    driverName: 'S. Kumar',
    busId: 'b1',
    busNumber: 'BUS-001',
    routeId: 'r1',
    routeName: 'Route A',
    date: subDays(today, 1).toISOString(),
    odometer: 48230,
    fuelAddedLitres: 45,
    fuelCost: 4275, // 45 * 95
    fuelStation: 'HP Auto Fuel Station, Sathyamangalam',
    remarks: 'Full tank refilled before evening trip.',
  },
  {
    id: 'fuel-102',
    driverId: 'd1',
    driverName: 'S. Kumar',
    busId: 'b1',
    busNumber: 'BUS-001',
    routeId: 'r1',
    routeName: 'Route A',
    date: subDays(today, 5).toISOString(),
    odometer: 47980,
    fuelAddedLitres: 50,
    fuelCost: 4750,
    fuelStation: 'Indian Oil, Annur Junction',
    remarks: 'Routine weekly fuel refill.',
  },
];

export const mockTripRecords: TripRecord[] = [
  {
    id: 'trip-201',
    driverId: 'd1',
    driverName: 'S. Kumar',
    busId: 'b1',
    busNumber: 'BUS-001',
    routeId: 'r1',
    routeName: 'Route A',
    date: todayStr,
    startTime: '07:30 AM',
    endTime: '08:45 AM',
    distanceCovered: 32,
    stopsCovered: 6,
    studentsPresent: 42,
    studentsAbsent: 3,
    status: 'Completed',
    notes: 'Smooth morning pickup trip completed on schedule.',
  },
  {
    id: 'trip-202',
    driverId: 'd1',
    driverName: 'S. Kumar',
    busId: 'b1',
    busNumber: 'BUS-001',
    routeId: 'r1',
    routeName: 'Route A',
    date: subDays(today, 1).toISOString(),
    startTime: '04:30 PM',
    endTime: '06:00 PM',
    distanceCovered: 32,
    stopsCovered: 6,
    studentsPresent: 45,
    studentsAbsent: 0,
    status: 'Completed',
    notes: 'Evening return trip.',
  },
  {
    id: 'trip-203',
    driverId: 'd1',
    driverName: 'S. Kumar',
    busId: 'b1',
    busNumber: 'BUS-001',
    routeId: 'r1',
    routeName: 'Route A',
    date: subDays(today, 3).toISOString(),
    startTime: '07:30 AM',
    endTime: '09:05 AM',
    distanceCovered: 34,
    stopsCovered: 6,
    studentsPresent: 40,
    studentsAbsent: 5,
    status: 'Delayed',
    notes: 'Delayed 20 mins due to Annur bridge construction traffic.',
  },
];

export const mockCalendarEvents: CalendarScheduleEvent[] = [
  {
    id: 'cal-1',
    title: 'Regular Academic Transport Duty',
    date: today.toISOString().split('T')[0],
    category: 'Working Day',
    description: 'Morning pickup at 07:30 AM & Evening drop at 04:30 PM.',
    assignedDriverId: 'd1',
  },
  {
    id: 'cal-2',
    title: 'Independence Day Holiday',
    date: '2026-08-15',
    category: 'Holiday',
    description: 'National Holiday. No regular bus service.',
  },
  {
    id: 'cal-3',
    title: 'Semester End Examination Transport',
    date: '2026-08-20',
    category: 'Exam',
    description: 'Special exam schedule. Extra afternoon trip at 01:30 PM.',
    assignedDriverId: 'd1',
  },
  {
    id: 'cal-4',
    title: 'BIT Convocation Special Duty',
    date: '2026-08-25',
    category: 'Special Bus Duty',
    description: 'VIP Guest & Alumni shuttle duty between Airport and Campus.',
    assignedDriverId: 'd1',
  },
  {
    id: 'cal-5',
    title: 'BUS-001 Scheduled Maintenance',
    date: '2026-08-28',
    category: 'Maintenance Day',
    description: 'Oil change and brake lining inspection at BIT Central Workshop.',
    assignedDriverId: 'd1',
  },
];
